#begin Added line
[build.environment]
DART_SASS_VERSION = "1.92.1"
GO_VERSION = "1.25.1"
HUGO_VERSION = "0.150.0"
NODE_VERSION = "22.18.0"    
#end

[build]
publish = "public"
#command = "hugo --gc --minify"
#command = "hugo --gc --minify --baseURL https://composedocs.netlify.app/"
command = """\
  curl -sLJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  tar -C "${HOME}/.local" -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  rm "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  export PATH="${HOME}/.local/dart-sass:${PATH}" && \
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """

[context.production.environment]
HUGO_VERSION = "0.147.2"
GO_VERSION = "1.21.0"
NODE_VERSION = "20.5.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.147.2"
GO_VERSION = "1.21.0"
NODE_VERSION = "20.5.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.147.2"
GO_VERSION = "1.21.0"
NODE_VERSION = "20.5.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.147.2"
GO_VERSION = "1.21.0"
NODE_VERSION = "20.5.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
