#  menu items
[[main]]
  name = "Serviços"
  weight = 1
  url = "services/"


[[main]]
  name = "Contatos"
  weight = 2
  url = "contacts/"

[[main]]
  name = "Redes Sociais"
  weight = 3
  url = "networks/"

[[main]]
  name = "Sobre"
  weight = 4
  url = "about/"
