#  menu items
[[main]]
  name = "Serviços"
  weight = 1
  url = "tutorials/"


[[main]]
  name = "Contatos"
  weight = 2
  url = "blog/"

[[main]]
  name = "Redes Sociais"
  weight = 3
  url = "docs/"

[[main]]
  name = "Sobre"
  weight = 4
  url = "sobre/"
